# Generated by Django 4.0.4 on 2024-04-15 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='card',
            name='box',
            field=models.IntegerField(choices=[(1, 1), (2, 2)], default=1),
        ),
    ]
